### ISSUE TITLE
Mac Bug to investigate

### ISSUE THREAD

**Issue by christophwille** [christophwille/ilspy-pscore#1]
import-module && get-assembly work fine (as well as outputting $asm) - but any other cmdlet that takes parameters crashes like this
```
PS /Users/christophw/GitWorkspace/ilspy-pscore/src/ICSharpCode.Decompiler.PSCore/bin/Debug/netstandard2.0> $classes = Get-DecompiledTypes $asm -Types class
Get-DecompiledTypes : Specified argument was out of the range of valid values.
At line:1 char:12
+ $classes = Get-DecompiledTypes $asm -Types class
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-DecompiledTypes], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,ICSharpCode.Decompiler.PSCore.GetDecompiledTypesCmdlet
```

.NET Core (2.0.2), VSMac on the machine.

**Comment by christophwille** [comment]
On Windows, it works
```
PS D:\GitWorkspace\ilspy-pscore\src> Import-Module .\ICSharpCode.Decompiler.PSCore\bin\Debug\netstandard2.0\ICSharpCode.
Decompiler.PSCore.dll
PS D:\GitWorkspace\ilspy-pscore\src> $asm = Get-Assembly .\ICSharpCode.Decompiler.PSCore\bin\Debug\netstandard2.0\ICShar
pCode.Decompiler.Extensions.dll
PS D:\GitWorkspace\ilspy-pscore\src> $classes = Get-DecompiledTypes $asm -Types class
PS D:\GitWorkspace\ilspy-pscore\src> foreach ($c in $classes)
>> {
>>     Write-Output $c.FullName
>> }
<Module>
ICSharpCode.Decompiler.Extensions.CustomAssemblyResolver
ICSharpCode.Decompiler.Extensions.SimpleAssemblyLoader
ICSharpCode.Decompiler.Extensions.SimpleDecompiler
ICSharpCode.Decompiler.Extensions.SimpleDecompiler.<ListContent>d__13
ICSharpCode.Decompiler.Extensions.SimpleDecompiler.<>c__DisplayClass17_0
ICSharpCode.Decompiler.Extensions.TypesParser
ICSharpCode.Decompiler.Extensions.TypesParser.<>c__DisplayClass0_0
PS D:\GitWorkspace\ilspy-pscore\src> $PSVersionTable.PSVersion

Major Minor Patch Label
----- ----- ----- -----
    6     0     0 beta.8
```

**Comment by christophwille** [comment]
Re-verified with Beta 9, still the same problem (brew cask didn't yet have the new version)

**Comment by christophwille** [comment]
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mono.Collections.Generic.Collection`1.get_Item(Int32 index)
   at Mono.Cecil.BaseAssemblyResolver.GetAssemblyInNetGac(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at ICSharpCode.Decompiler.Extensions.CustomAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
 in /Users/christophw/GitWorkspace/ilspy-pscore/src/ICSharpCode.Decompiler.Extensions/CustomAssemblyResolver.cs:line 75
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at ICSharpCode.Decompiler.Extensions.CustomAssemblyResolver.Resolve(AssemblyNameReference name) in
/Users/christophw/GitWorkspace/ilspy-pscore/src/ICSharpCode.Decompiler.Extensions/CustomAssemblyResolver.cs:line 45
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(ModuleDefinition moduleDefinition)
   at ICSharpCode.Decompiler.Extensions.SimpleDecompiler.Create(ModuleDefinition module) in
/Users/christophw/GitWorkspace/ilspy-pscore/src/ICSharpCode.Decompiler.Extensions/SimpleDecompiler.cs:line 39
   at ICSharpCode.Decompiler.PSCore.GetDecompiledSourceCmdlet.ProcessRecord() in
/Users/christophw/GitWorkspace/ilspy-pscore/src/ICSharpCode.Decompiler.PSCore/GetDecompiledSourceCmdlet.cs:line 24
```

**Comment by christophwille** [comment]
Next investigation steps:

Take ilspycmd prototype. Re-run (2.0 netcore to 2.0.2 on Mac)
Update from alpha2 to -beta (when we switched from Debug builds to Release)
Take official console and test

Also of note: we are always building Cecil net_40. Wouldn't it better on Nuget builds to have a solution configuration Release_Netstandard and use Release_Netstandard on Cecil?

**Comment by christophwille** [comment]
check 1: prototype as-is work
check 2: prototype with beta1 nuget works
check 3: prototype using the new ics.d.extensions (listcontent, decompile) works

-> there's something that PS does differently compared to a bash

**Comment by christophwille** [comment]
Only happens for netstandard dlls (eg ics.d.pscore.dll), netcore are fine (eg ilspycmd.dll). Same behavior also occurs for ./ilspycmd - this is not limited to PS scenario.

var dp = new DotNetCorePathFinder(path, ".NETStandard,Version=v2.0", "v2.0");

packages are empty.

**Comment by christophwille** [comment]
Fix: https://github.com/icsharpcode/ILSpy/commit/79ef84426ab76437c30301d1697bbd23d160703d
